---
title: "Johdantoluento"
subtitle: "Mielenterveyden sosiaaliset determinantit: Rekisteritutkimus"
author: "Kimmo Suokas"
date: "2024-04-12"
navbar: false
---

## Avaus

Arvoisa kustos, arvoisa vastaväittäjä, arvoisat kuulijat,

Miksi on tärkeää tutkia mielenterveyteen liittyviä sosiaalisia tekijöitä? Miksi lääkärit eivät keskity lääketieteellisiin tekijöihin, joku saattaisi kysyä.

Yksinkertaisen vastauksen tähän kysymykseen kuulin Psykiatrian maailmankongressissa Madridissa vuonna 2014.

Maailman psykiatriyhdistyksen silloinen presidentti Dinesh Bhugra ilmaisi asian hyvin aselkeästi:

## Kaikki psykiatria on sosiaalista - Dinesh Bhugra

Täällä yhteiskuntatieteiden tiedekunnassa tämä lausunto saattaa vaikuttaa itsestään selvältä. Kuitenkin noina aikoina ei ollut harvinaista lukea mielipiteitä kuten "Psykiatrian tulevaisuus on kliinisessä neurotietessä" arvostetuilta kirjoittajilta kuten Thomas Insel, entinen National Institute of Mental Health -instituutin johtaja Yhdysvalloissa.

Saattaa olla niin, mutta tässä valossa koin lauseen "Kaikki psykiatria on sosiaalista" tuoreena ja jopa hieman radikaalina.

Mutta mitä tarkoittaa, että kaikki psykiatria on sosiaalista?

On selvää, että yksilöt toimivat aina osana erilaisia sosiaalisia järjestelmiä ja rakenteita, ja sosiaalinen vuorovaikutus on keskeistä mielenterveyden kannalta, määritelmän mukaankin. Lisäksi vuorovaikutus on tietenkin keskeinen osa kliinistä psykiatriaa.

Lisäksi erilaiset sosiaaliset normit ja odotukset vaikuttavat psykiatriaan, niin diagnostikkaan kuin hoitoonkin. Uskon, että niin on aina ollut ja niin on aina oleva. Mielestäni se on enemmän psykiatrian vahvuus kuin heikkous.

Mutta on vielä muutakin. Kyseisessä kongressissa käsiteltiin kysymyksiä syrjinnästä ja muista mielenterveyshäiriöihin liittyvistä haitallisista seurauksista sekä yleisestä sosiaalisesta oikeudenmukaisuudesta. Esimerkiksi Euroopan entisissä siirtomaissa psykiatrisissa laitoksissa ja lainsäädännössä saattaa olla piirteitä, jotka eivät koskaan ole olleet sopusoinnussa paikallisten tapojen ja käytänteiden kanssa. Monissa maissa perheenjäsenet kantavat kohtuutonta taakaa sukulaistensa hoidosta. Dinesh Bhugra oli johtanut tutkimusta, joka osoittaa, että monissa maissa mielenterveysongelmaisilta ihmisiltä evätään edelleen heidän äänioikeutensa tai muita perusoikeuksia.

Olen varma, että tällainen globaali epäoikeudenmukaisuus resonoi mielenterveysalalla työskentelevien piirissä.

Mutta mitä sokeita pisteitä liittyy psykiatriaan Suomessa? Kliinisen kokemukseni perusteella tuolloin epäilin, että kyse ei ole vain yhteiskunnallisista tekijöistä, vaan ongelmia saattaa olla myös terveydenhuoltojärjestelmässä. Todellakin, löytyy tutkimusartikkeleita, jotka osoittavat esimerkiksi, että ihmiset, joilla on diagnosoitu psykoottisia mielenterveyden häiriöita, saavatusein vähemmän intensiivistä ja vähemmän tehokasta hoitoa sydänsairauksiin kuin muut jopa Suomessa. Olin  yllättynyt siitä, miten vähän tämä asia oli esillä.

Mutta mitä tulee psykiatriaan itseensä? Kiinnostuin siitä, ovatko diagnosointikäytännöissä eroja, jotka saattavat liittyä mielenterveyshäiriöiden epätasa-arvoihin. Vaikka alun perin tutkimussuunnitelmani oli tutkia tätä hypoteesia tohtorinprojektissani, huomasin, että on muitakin perustavanlaatuisia sosiaalisesti suuntautuneita psykiatrisia epidemiologisia aiheita, joihin kannattaa ensin syventyä.

Puhuttaessa sosiaalisista tekijöistä mielenterveydessä on hyvä pitää mielessä, että tämä teema sijoittuu pitkälle tieteelliselle jatkumolle. Siksi haluaisin jakaa toisen lainauksen:

## Lääketiede on sosiaalitiedettä ja politiikka on lääketiedettä isossa mittakaavassa - Rudolf Virchow, 1848

Patologian oppikirjat kutsuvat usein Virchowia solupatologian perustajaksi. Se on teoria, jonka mukaan kaikki sairaudet voidaan ymmärtää solujen toiminnan ja toimintahäiriöiden perusteella.

Teknisesti tämä lausunto ei ole tietenkään täysin totta, mutta tätä lausetta siteerataan melko yleisesti kansanterveysalan kirjallisuudessa. Luulen, että ihmiset ovat lumoutuneita tämän näkökulman kokonaisvaltaisuudesta, kun se on sanonut henkilö, joka oli niin merkittävä solujen ja patologian tutkija.

Niin tai näin, tässä valossa "kaikki psykiatria on sosiaalista" ei ehkä ole enää niin radikaali.

Näitä iskulauseita pohtiessaan joku voisi kysyä, mitä "sosiaalinen" tarkalleen tarkoittaa. Tämän tutkimuksen tarkoitus ei kuitenkaan ole käsitellä "sosiaalinen" konseptuaalista merkitystä, vaan pikemminkin pyrkii ymmärtämään mielenterveyden sosiaalisia determinantteja.

Mitkä sitten ovat sosiaaliset determinantit?

## Sosiaaliset determinantit

On huomattava, että englanti-suomi-sanakirjoissa "determinant" käännetään usein ilmaisuksi "määräävä tekijä", mikä viittaa hyvin vahvaan syy-yhteyteen. Lisäksi filosofiassa on termi determinismi, joka voi edelleen vahvistaa tätä merkitystä.

Kuitenkin, kuten määritelmässä todetaan, tässä keskitytään poliittisiin, kulttuurisiin, taloudellisiin ja muihin ei-lääketieteellisiin tekijöihin, jotka muokkaavat yhteiskuntaa ja ihmisten mahdollisuuksia terveelliseen elämään ja siten vaikuttavat terveyteen.

THL:n mukaan determinantti voidaan kääntää sanoiksi "määrittäjä" tai "taustatekijä".

Puhuttaessa vahvoista syy-yhteyksistä, vielä yksi tunnettu lainaus:

## Assosiaatio ei todista syy-yhteyttä

Tämä lausunto on tärkeä mutta samalla ilmeinen. Kuitenkin vähemmän ilmeistä on, mitkä tekijät todella viittaavat syy-yhteyteen.

Päästäkseni syvemmälle tähän kysymykseen, haluaisin esitellä vielä muutamia poleemisia sitaatteja: 

### Syyn ja seurauksen laki, uskon, kuten moni muu filosofien hyväksymä asia, on menneen ajan jäänne, joka selviää, kuten monarkia, vain siksi, että virheellisesti uskotaan että se ei aiheuta vahinkoa - Bertrand Russell, 1912

### Epidemiologia pyrkii olemaan tarkka ja kvantitatiivinen, mutta meillä ei ole tarkkaa - saati sitten kvantitatiivista - määritelmää syy-yhteydestä, huolimatta tuhansista vuosista yrityksiä.

### Epidemiologit löytävät näin itsensä hankalassa tilanteessa, haluten sanoa, tarkasti kvantitatiivisesti, asioita, joita ihmiset ovat tähän mennessä pystyneet sanomaan vain epämääräisesti ja laadullisesti

Vandenbroucke et al., 2016

Mielenterveyden sosiaalisten determinanttien osalta tämä on tärkeä asia, koska

### The paradox is that the closer we get to identifying a true causal effect, the farther we may get from a good understanding of how socioeconomic position affects health - Mackenbach, 2019

Näillä ajatuksilla haluan korostaa sitä, että terveyen sosiaalisten determinanttien tutkiminen on monimutkaista, koska monet asiat vaikuttavat samaan aikaan.

Tulojen ja terveyden tapauksessa on erityisen ilmeistä, että rahan jakautuminen yhteiskunnassa määräytyy - tai aiheutuu - muista monimutkaisista tekijöistä, kuten henkilökohtaiset ominaisuudet, sosiaalinen liikkuvuus, poliittiset valinnat, maailmantalous jne.

Tulonjako ei ole mikään luonnonvakio.

Syiden ja seurauksen tunnistamisen vaikeus tulee ottaa vakavasti, mutta sen ei pidä estää meitä käsittelemästä terveyden sosiaalisia määrääjiä. Tässä on esimerkki:

## Kuva

Tämä Christian Hakulisen kuva havainnollistaa joitain keskeisiä näkökohtia tulojen ja mielenterveysongelmien välisestä suhteesta.

Tässä näemme mediaanitulot ennen ja jälkeen ensimmäisen psykoosin vuoksi olleen sairaalahoitojakson. Onko tämä ero alussa psykoosin syy?

Toinen tärkeä asia on mitä tapahtuu ensimmäisen hoitojakson jälkeen. Tätä kutsutaan usein valikoitumiseksi tai käänteiseksi syy-seuraussuhteeksi. Sanotaan, että olet lapsi tässä perheessä, tai tässä vertailuperheessä, mitä tämä ero saattaa merkitä sinulle terveyden määrääjien tai tulevaisuuden mahdollisuuksiesi kannalta? Tai toisin päin, mihin suuntaan tämän viivan tulisi mennä? Kiitos järjestelmämme, kokonaistulot pysyvät vakaana sairastumisen jälkeen, mutta mikä olisi optimaalisin tilanne?

Virchowin lausahusa mukaillen väitän, että tämä ei ole lääketiedettä suuremmassa mittakaavassa. Tämä on politiikkaa suuremmassa mittakaavassa. Kysymys on siitä millaisia hyvinvoinnin standardeja haluamme pohjoismaisessa yhteiskunnassamme ylläpitää.

Tämä väitöskirja ei tuo tähän kysymykseen mitään valmista vastusta, mutta mielestäni Suomessa, maailman onnellisimmaksi valitussa maassa, meidän pitäisi olla aktiivisempia johtamaan keskustelua tasa-arvosta ja terveydestä.

Haluaisin nostaa esiin vielä kaksi asiaa:

Ensinnäkin, tämä tutkimus ei käsittele tuloeroja, mutta ne ovat luonnollisesti läheisessä yhteydessä terveyden epätasa-arvoon.

"Inequalities" voidaan kääntää ilmaisuilla 'epätasa-arvo' tai 'eriarvoisuus'. Ne ovat eroja, jotka ovat jollain tavalla epäoikeudenmukaisia, epäreiluja luonteeltaan, joskin englannin kieli ei ole tässä täysin johdonmukainen. Inequalities voi joskus viitata eroihin ilman mitään moraalista arviota.

Onko tuloerot kasvaneet Suomessa vai ei, on kiinnostava kysymys. Valitsin olla kommentoimatta sitä väitöskirjassani, mutta nämä kaksi kuvaa valaisee asiaa:

## Kuvat

Ensin Gini-kerroin, jonka suuremmat arvot kuvaavat suurempia tuloeroja. Esim. Valtion taloudelllinen tutkimuslaitos juuri julkaisi raportin, jonka mukaan tuloerot eivät juurikaan ole muuttuneet 2000-luvulla.

Toisessa kuvassa tulojen kehitys tulokymmenyksittäin. 1995-2022, muutos oli 26 % alimmassa tulokymmenyksessä, mutta 91 % ylimmässä.

Myöhemmin katsomme muita trendejä tulokymmenyksittäin.


## Avoin tiede

Ja lopuksi: Tämän projektin ensimmäisen tutkimussuunnitelma valmistui helmikuussa 2016, sain pääsyn aineistoon maaliskuussa 2017. Ensimmäisen käsikirjoituksen valmisteluun meni 2 vuotta ja 2 kuukautta.

Suurin osa siitä työstä oli opetella esikäsittelemään rekisteridataa. Jotain, mikä on pitänyt tehdä ennen jokaista rekisteritutkimusta.

Se oli valtava ponnistus ja voi kysyä, kuinka järkevää on tehdä samaa työtä uudestaan ja uudestaan.

Tämä projekti on tehnyt minusta avoimen tieteen periaatteiden kannattajan, ja olen yrittänyt tehdä oman osuuteni julkaisemalla keskeisiä ohjelmakoodeja, jotka ovat tarpeen terveydenhuollon rekisterien esikäsittelyssä.

Mielestäni jokaisen, joka suhtautuu tieteelliseen metodiin vakavasti, tulisi tehdä parhaansa jakaakseen menetelmänsä, vaikka kukaan ei edes pyytäisi. Minulle siitä olisi ollut valtava hyöty, ja toivon, että mahdolliset tulevat tutkijat voivat hyötyä edes hieman omasta panoksestani.





